/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikacja;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import klasy.*;
import wykresy.Wykres3;

/**
 *
 * @author Elater
 */


public class GUIgielda extends javax.swing.JInternalFrame {
    
private GUIspolka guispolka = new GUIspolka();
//private Wykres3 wykres;
private JButton buttonInfo;
boolean pressingCTRL=false;//flag, if pressing CTRL it is true, otherwise it is false.
Vector selectedCells = new Vector<int[]>();//int[]because every entry will store {cellX,cellY}
List <Integer> newEntry = new ArrayList<>();
/**
     * Creates new form GUIinwestorzy
     */
    public GUIgielda() throws FileNotFoundException, IOException {
        
        setLocation(310, 60);
        initComponents();
        fillData();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSpolek = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buttomLosuj = new javax.swing.JButton();
        buttomDodaj = new javax.swing.JButton();
        buttoInfo = new javax.swing.JButton();
        buttoWykresy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text7 = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Lista spółek");

        tabelaSpolek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaSpolek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSpolekMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSpolek);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacje o giełdzie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        buttomLosuj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomLosuj.setText("Losuj");
        buttomLosuj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomLosuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomLosujActionPerformed(evt);
            }
        });

        buttomDodaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomDodaj.setText("Dodaj");
        buttomDodaj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomDodajActionPerformed(evt);
            }
        });

        buttoInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttoInfo.setText("Info");
        buttoInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoInfoActionPerformed(evt);
            }
        });

        buttoWykresy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttoWykresy.setText("Rysuj wykresy");
        buttoWykresy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoWykresy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoWykresyActionPerformed(evt);
            }
        });

        jLabel1.setText("Nazwa:");

        jLabel2.setText("Waluta:");

        jLabel3.setText("Miasto:");

        jLabel7.setText("Kraj:");

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Adres:");

        text5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Lista indeksów:");

        jLabel9.setText("Marża proc.:");

        text7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text7ActionPerformed(evt);
            }
        });

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttoInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttomLosuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttoWykresy, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(buttomDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text2)
                            .addComponent(text1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text7)
                            .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(45, 45, 45)
                        .addComponent(text5)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttomLosuj)
                    .addComponent(buttomDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttoInfo)
                    .addComponent(buttoWykresy))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttomLosujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomLosujActionPerformed
        
        try {
            Spolka inw = new Spolka();
            text1.setText(inw.getNazwa());
            text2.setText(inw.getDataPierwszejWyceny());
            text3.setText(Double.toString(inw.getKursOtwarcia()));
            text4.setText(Integer.toString(inw.getLiczbaAkcji()));
            text5.setText(Double.toString(inw.getKapitalWlasny()));
            //text6.setText(Double.toString(inw.getKapitalZakladowy()));
            //textBudzet.setText(Integer.toString(inw.getBudzetInwestycyjny()));
        } catch (IOException ex) {
            Logger.getLogger(GUIgielda.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_buttomLosujActionPerformed

    private void buttomDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomDodajActionPerformed
      // Spolka inw = new Spolka(text1.getText(),text2.getText(),Double.parseDouble(text3.getText()),Double.parseDouble(text3.getText()),
            //  Double.parseDouble(text3.getText()),Double.parseDouble(text3.getText()),Integer.parseInt(text4.getText()), 
             // 0,0,Double.parseDouble(text5.getText()),Double.parseDouble(text6.getText()),0,0);
       
        try {
            boolean unikat=true;
            for(Spolka in: Main.listaSpolek)
            {
                if(in.getNazwa().equals(text1.getText())) unikat=false;
            }
            if(unikat==true) 
            {
               // Main.listaSpolek.add(inw);
                fillData();
            }
        } catch (IOException ex) {
            Logger.getLogger(GUIgielda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttomDodajActionPerformed

    private void tabelaSpolekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSpolekMouseClicked
          KeyListener tableKeyListener = new KeyAdapter() {

      @Override
      public void keyPressed(KeyEvent e) {
         if(KeyEvent.VK_CONTROL==e.getKeyCode()){//check if user is pressing CTRL key
            pressingCTRL=true;
         }
      }

      @Override
      public void keyReleased(KeyEvent e) {
         if(e.getKeyCode()==KeyEvent.VK_CONTROL){//check if user released CTRL key
            pressingCTRL=false;
         }
      }
        //buttonInfo.setEnabled(true);
          };
          MouseListener tableMouseListener = new MouseAdapter() {

      @Override
      public void mouseClicked(MouseEvent e) {
         if(pressingCTRL){//check if user is pressing CTRL key
            int row = tabelaSpolek.rowAtPoint(e.getPoint());//get mouse-selected row
            //int col = tabelaSpolek.columnAtPoint(e.getPoint());//get mouse-selected col
            newEntry.add(row);//{row,col}=selected cell
            if(selectedCells.contains(newEntry)){
               //cell was already selected, deselect it
               selectedCells.remove(newEntry);
            }else{
               //cell was not selected
               selectedCells.add(newEntry);
            }
         }
      }
   };
   tabelaSpolek.addKeyListener(tableKeyListener);
   tabelaSpolek.addMouseListener(tableMouseListener);

    }//GEN-LAST:event_tabelaSpolekMouseClicked

    private void buttoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoInfoActionPerformed
       if(!guispolka.isVisible())
        {
            guispolka.setVisible(true);
            JDesktopPane desktopPane = (JDesktopPane) getParent();
            desktopPane.add(guispolka);
                Spolka sp;
            try {
                sp = new Spolka();
                int currentRow = tabelaSpolek.getSelectedRow();
                guispolka.fillData(sp.szukaj(tabelaSpolek.getValueAt(currentRow, 0).toString()));
            } catch (IOException ex) {
                Logger.getLogger(GUIgielda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                Spolka sp = new Spolka();
                int currentRow = tabelaSpolek.getSelectedRow();
                guispolka.fillData(sp.szukaj(tabelaSpolek.getValueAt(currentRow, 0).toString()));
                
            } catch (IOException ex) {
                Logger.getLogger(GUIgielda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttoInfoActionPerformed

    private void buttoWykresyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoWykresyActionPerformed
        List <Spolka> listaNaWykres = new ArrayList<>();
        for (int i=0; i<newEntry.size(); i++)
        listaNaWykres.add(Main.listaSpolek.get(newEntry.get(i)));
        try {
            Wykres3 wykres = new Wykres3(listaNaWykres);
        } catch (IOException ex) {
            Logger.getLogger(GUIgielda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttoWykresyActionPerformed

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text5ActionPerformed

    private void text7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text7ActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed
public void fillData() throws FileNotFoundException, IOException
	{
            
		DefaultTableModel defaultTableModel = new DefaultTableModel();
		defaultTableModel.addColumn("Nazwa");
		defaultTableModel.addColumn("D.P.Wyceny");
		defaultTableModel.addColumn("Aktualny kurs");
		defaultTableModel.addColumn("L. akcji");
		defaultTableModel.addColumn("Kapitał własny");
		defaultTableModel.addColumn("Kapitał zakładowy");
		defaultTableModel.addColumn("Przychód");
		Spolka inw = new Spolka();
		for(Spolka in: Main.listaSpolek)
                {
                    //System.out.println("robimy coś");
			defaultTableModel.addRow(new Object[] {in.getNazwa(),in.getDataPierwszejWyceny(),
                            in.getAktualnyKurs(),in.getLiczbaAkcji(), in.getKapitalWlasny(), in.getKapitalZakladowy(),in.getPrzychod()});
                        //in.wyswietl();
                        
                }
		tabelaSpolek.setModel(defaultTableModel);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoInfo;
    private javax.swing.JButton buttoWykresy;
    private javax.swing.JButton buttomDodaj;
    private javax.swing.JButton buttomLosuj;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaSpolek;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text7;
    // End of variables declaration//GEN-END:variables
}
