/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikacja;

import inwestujacy.Inwestor;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import klasy.*;
import odswiezanie.OdswiezanieInd;
import odswiezanie.OdswiezanieSpo;
import wykresy.Wykres3;

/**
 *
 * @author Elater
 */


public class GUIgieldy extends javax.swing.JInternalFrame {
    
private GUIindeks guiindeks = new GUIindeks();
private Wykres3 wykres;
private JButton buttonInfo;
String[] messageString ={ "Wybierz giełdę"};
JComboBox cmbMessageList = new JComboBox(messageString);
//JComboBox jComboBox = new JComboBox();
/**
     * Creates new form GUIinwestorzy
     */
    public GUIgieldy() throws FileNotFoundException, IOException {
        
        setLocation(300, 50);
        initComponents();
        jComboBox.setEnabled(false);
        jComboBox.addItem("Wybierz giełdę");
        jComboBox.setSelectedItem("Wybierz giełdę");
        fillData();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGield = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        buttomLosuj = new javax.swing.JButton();
        buttomDodaj = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        textIndeks = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Lista giełd");

        tabelaGield.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaGield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaGieldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaGield);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nowa giełda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setText("Nazwa:");

        jLabel2.setText("Waluta:");

        jLabel3.setText("Miasto:");

        buttomLosuj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomLosuj.setText("Losuj");
        buttomLosuj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomLosuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomLosujActionPerformed(evt);
            }
        });

        buttomDodaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomDodaj.setText("Dodaj");
        buttomDodaj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomDodajActionPerformed(evt);
            }
        });

        jLabel7.setText("Kraj:");

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Lista indeksów:");

        text6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text6ActionPerformed(evt);
            }
        });

        jLabel9.setText("Marża proc.:");

        text7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text7ActionPerformed(evt);
            }
        });

        jLabel10.setText("Adres:");

        text5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text5ActionPerformed(evt);
            }
        });

        jComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Indeksy:");

        textIndeks.setEditable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("->");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text2)
                            .addComponent(text1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttomLosuj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(buttomDodaj))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text5)
                            .addComponent(text3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text6)
                            .addComponent(text7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textIndeks)
                            .addComponent(jComboBox, 0, 207, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttomLosuj)
                    .addComponent(buttomDodaj))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttomLosujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomLosujActionPerformed
        
        try {
            Gielda inw = new Gielda();
            text1.setText(inw.getNazwa());
            text2.setText(inw.getWaluta().getNazwa());
            text3.setText(inw.getMiasto());
            text4.setText(inw.getKraj());
            text5.setText(inw.getAdresSiedziby());
            String indeksy = "";
            for(Indeks i: inw.getListaIndeksow())
            {
                indeksy+=i.getNazwa()+", ";
            }
            text6.setText(indeksy);
            text7.setText(Double.toString(inw.getMarzaProc()));
            //textBudzet.setText(Integer.toString(inw.getBudzetInwestycyjny()));
        } catch (IOException ex) {
            Logger.getLogger(GUIgieldy.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_buttomLosujActionPerformed

    private void buttomDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomDodajActionPerformed
       int i=0;
        for (i=0; i<Main.listaWalut.size(); i++)
        {
            if (text2.getText().equals(Main.listaWalut.get(i).getNazwa())) 
            {
                break;
            }
            
        }
        /*
        Gielda inw = new Gielda(text1.getText(),wal,text3.getText(),Double.parseDouble(text3.getText()),
              Double.parseDouble(text3.getText()),Double.parseDouble(text3.getText()),Integer.parseInt(text4.getText()), 
               0,0,Double.parseDouble(text6.getText()),Double.parseDouble(text7.getText()),0,0);*/
        List <Indeks> lista = new ArrayList<>();
        
            String splited = text6.getText();
            String[] splitedArray = null;
            splitedArray = splited.split(", ");
            for(int j=0; j<4; j++)
            {
           try {
               Indeks idx = new Indeks(splitedArray[j]);
               lista.add(idx);
               Main.listaIndeksow.add(idx);
               
           } catch (IOException ex) {
               Logger.getLogger(GUIgieldy.class.getName()).log(Level.SEVERE, null, ex);
           }
            }
        
        Gielda inw = new Gielda(text1.getText(),Main.listaWalut.get(i),text3.getText(), text4.getText(), text5.getText(), lista,Double.parseDouble(text7.getText()));
       
        try {
            boolean unikat=true;
            for(Gielda in: Main.listaGield)
            {
                if(in.getNazwa().equalsIgnoreCase(text1.getText())) unikat=false;
            }
            if(unikat==true) 
            {
                Main.listaGield.add(inw);
                fillData();
            }
        } catch (IOException ex) {
            Logger.getLogger(GUIsurowce.class.getName()).log(Level.SEVERE, null, ex);
        }
                                    
      
        /*
        Gielda inw = null;
    try {
        inw = new Gielda();
    } catch (IOException ex) {
        Logger.getLogger(GUIgieldy.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        try {
            boolean unikat=true;
            for(Gielda in: Main.listaGield)
            {
                if(in.getNazwa().equalsIgnoreCase(text1.getText())) unikat=false;
            }
            if(unikat==true) 
            {
                Main.listaGield.add(inw);
                fillData();
            }
        } catch (IOException ex) {
            Logger.getLogger(GUIgieldy.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_buttomDodajActionPerformed

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void text6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text6ActionPerformed

    private void text7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text7ActionPerformed

    private void tabelaGieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaGieldMouseClicked
          jComboBox.setEnabled(true);
          jComboBox.removeAllItems();
          int currentRow = tabelaGield.getSelectedRow();
          String wszystko = tabelaGield.getValueAt(currentRow, 5).toString();
          String[] splitedArray = null;
          splitedArray = wszystko.split(", ");
          jComboBox.addItem(splitedArray[0]);
          jComboBox.addItem(splitedArray[1]);
          jComboBox.addItem(splitedArray[2]);
          jComboBox.addItem(splitedArray[3]);          
          
    }//GEN-LAST:event_tabelaGieldMouseClicked

    private void text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text5ActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        
        textIndeks.setText((String) jComboBox.getSelectedItem());
        //jButton1.setEnabled(true);
        
        
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(!guiindeks.isVisible())
        {
            Thread threadOdswiezanieInd = new Thread(new OdswiezanieInd(guiindeks));
             threadOdswiezanieInd.start();
            guiindeks.setVisible(true);
            JDesktopPane desktopPane = (JDesktopPane) getParent();
            desktopPane.add(guiindeks);
                Indeks sp;
            try {
                sp = new Indeks();
                for(Indeks id: Main.listaIndeksow)
                    if(id.getNazwa().equals(textIndeks.getText()))
                    { sp=id; break;}
                guiindeks.ustawNazwe(sp.getNazwa(), sp.getWynikIndeksu());
                guiindeks.fillData();
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                Indeks sp = new Indeks();
                for(Indeks id: Main.listaIndeksow)
                    if(id.getNazwa().equals(textIndeks.getText()))
                    {
                        sp=id;
                        break;
                    }
                guiindeks.ustawNazwe(sp.getNazwa(), sp.getWynikIndeksu());
                guiindeks.fillData();
                
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void fillData() throws FileNotFoundException, IOException
	{
            
		DefaultTableModel defaultTableModel = new DefaultTableModel();
		defaultTableModel.addColumn("Nazwa");
		defaultTableModel.addColumn("Waluta");
		defaultTableModel.addColumn("Miasto");
		defaultTableModel.addColumn("Kraj");
		defaultTableModel.addColumn("Adres siedziby");
		defaultTableModel.addColumn("Lista indeksów");
		defaultTableModel.addColumn("Marża");
		Gielda inw = new Gielda();                
                String indeksy = "";
                for(Indeks i: inw.getListaIndeksow())
                {
                    indeksy+=i.getNazwa()+", ";
                }
		for(Gielda in: Main.listaGield)
                {
                    //System.out.println("robimy coś");
			defaultTableModel.addRow(new Object[] {in.getNazwa(),in.getWaluta().getNazwa(),
                            in.getMiasto(),in.getKraj(), in.getAdresSiedziby(), in.wypisz(), in.getMarzaProc()});
                        //in.wyswietl();
                        
                }
		tabelaGield.setModel(defaultTableModel);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttomDodaj;
    private javax.swing.JButton buttomLosuj;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaGield;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JTextField textIndeks;
    // End of variables declaration//GEN-END:variables
}
