/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikacja;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import klasy.*;
import wykresy.*;

/**
 *
 * @author Elater
 */


public class GUIsurowce extends javax.swing.JInternalFrame {
    
private GUIsurowiec guisurowiec = new GUIsurowiec(this);
private Wykres1 wykres1;
boolean pressingCTRL=false;//flag, if pressing CTRL it is true, otherwise it is false.
Vector selectedCells = new Vector<int[]>();//int[]because every entry will store {cellX,cellY}
List <Integer> newEntry = new ArrayList<>();
/**
     * Creates new form GUIinwestorzy
     */
    public GUIsurowce() throws FileNotFoundException, IOException {
        
        setLocation(450, 40);
        initComponents();
                fillData();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSurowcow = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        buttomLosuj = new javax.swing.JButton();
        buttomDodaj = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text6 = new javax.swing.JTextField();
        buttonInfo = new javax.swing.JButton();
        buttoWykresy = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista surowców");

        tabelaSurowcow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaSurowcow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSurowcowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSurowcow);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nowy surowiec", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setText("Nazwa:");

        jLabel2.setText("Jednostka handlowa:");

        jLabel3.setText("Waluta:");

        buttomLosuj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomLosuj.setText("Losuj");
        buttomLosuj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomLosuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomLosujActionPerformed(evt);
            }
        });

        buttomDodaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomDodaj.setText("Dodaj");
        buttomDodaj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomDodajActionPerformed(evt);
            }
        });

        jLabel7.setText("Aktualna wartość:");

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Min wartość:");

        text5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Max wartość:");

        text6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text6ActionPerformed(evt);
            }
        });

        buttonInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonInfo.setText("Info");
        buttonInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoActionPerformed(evt);
            }
        });

        buttoWykresy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttoWykresy.setText("Rysuj wykresy");
        buttoWykresy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoWykresy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoWykresyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text2)
                                    .addComponent(text1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(text5)
                                    .addComponent(text6)
                                    .addComponent(text3, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttomLosuj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttoWykresy, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(buttomDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttomLosuj)
                    .addComponent(buttomDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInfo)
                    .addComponent(buttoWykresy))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttomLosujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomLosujActionPerformed
        
        try {
            Surowiec inw = new Surowiec();
            text1.setText(inw.getNazwa());
            text2.setText(inw.getJednostkaHandlowa());
            text3.setText("Złoty");
            text4.setText(Double.toString(inw.getAktualnaWartosc()));
            text5.setText(Double.toString(inw.getMinWartosc()));
            text6.setText(Double.toString(inw.getMaxWartosc()));
            //textBudzet.setText(Integer.toString(inw.getBudzetInwestycyjny()));
        } catch (IOException ex) {
            Logger.getLogger(GUIsurowce.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_buttomLosujActionPerformed

    private void buttomDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomDodajActionPerformed
       Waluta zloty = new Waluta("Złoty", Main.listaZlotowek,0.55,0.57);
        
        Surowiec inw = new Surowiec(text1.getText(),text2.getText(),
               zloty,Double.parseDouble(text4.getText()),
              Double.parseDouble(text5.getText()),Double.parseDouble(text6.getText()));
       
        try {
            boolean unikat=true;
            for(Surowiec in: Main.listaSurowcow)
            {
                if(in.getNazwa().equalsIgnoreCase(text1.getText())) unikat=false;
            }
            if(unikat==true) 
            {
                Main.listaSurowcow.add(inw);
                fillData();
            }
        } catch (IOException ex) {
            Logger.getLogger(GUIsurowce.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttomDodajActionPerformed

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text5ActionPerformed

    private void text6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text6ActionPerformed

    private void tabelaSurowcowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSurowcowMouseClicked
          KeyListener tableKeyListener = new KeyAdapter() {

      @Override
      public void keyPressed(KeyEvent e) {
         if(KeyEvent.VK_CONTROL==e.getKeyCode()){//check if user is pressing CTRL key
            pressingCTRL=true;
         }
      }

      @Override
      public void keyReleased(KeyEvent e) {
         if(e.getKeyCode()==KeyEvent.VK_CONTROL){//check if user released CTRL key
            pressingCTRL=false;
         }
      }
        //buttonInfo.setEnabled(true);
          };
          MouseListener tableMouseListener = new MouseAdapter() {

      @Override
      public void mouseClicked(MouseEvent e) {
         if(pressingCTRL){//check if user is pressing CTRL key
            int row = tabelaSurowcow.rowAtPoint(e.getPoint());//get mouse-selected row
            //int col = tabelaSpolek.columnAtPoint(e.getPoint());//get mouse-selected col
            newEntry.add(row);//{row,col}=selected cell
            if(selectedCells.contains(newEntry)){
               //cell was already selected, deselect it
               selectedCells.remove(newEntry);
            }else{
               //cell was not selected
               selectedCells.add(newEntry);
            }
         }
      }
   };
   tabelaSurowcow.addKeyListener(tableKeyListener);
   tabelaSurowcow.addMouseListener(tableMouseListener);

    }                                         

    private void buttoInfoActionPerformed(java.awt.event.ActionEvent evt) {                                          
       if(!guisurowiec.isVisible())
        {
            guisurowiec.setVisible(true);
            JDesktopPane desktopPane = (JDesktopPane) getParent();
            desktopPane.add(guisurowiec);
                Surowiec sp;
            try {
                sp = new Surowiec();
                int currentRow = tabelaSurowcow.getSelectedRow();
                guisurowiec.fillData(sp.szukaj(tabelaSurowcow.getValueAt(currentRow, 0).toString()));
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                Surowiec sp = new Surowiec();
                int currentRow = tabelaSurowcow.getSelectedRow();
                guisurowiec.fillData(sp.szukaj(tabelaSurowcow.getValueAt(currentRow, 0).toString()));
                
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    

    }//GEN-LAST:event_tabelaSurowcowMouseClicked

    private void buttonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoActionPerformed
        if(!guisurowiec.isVisible())
        {
            guisurowiec.setVisible(true);
            JDesktopPane desktopPane = (JDesktopPane) getParent();
            desktopPane.add(guisurowiec);
            Surowiec sp;
            try {
                sp = new Surowiec();
            } catch (IOException ex) {
                Logger.getLogger(GUIsurowce.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                sp = new Surowiec();
                int currentRow = tabelaSurowcow.getSelectedRow();
                guisurowiec.fillData(sp.szukaj(tabelaSurowcow.getValueAt(currentRow, 0).toString()));
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                Surowiec sp = new Surowiec();
                int currentRow = tabelaSurowcow.getSelectedRow();
                guisurowiec.fillData(sp.szukaj(tabelaSurowcow.getValueAt(currentRow, 0).toString()));

            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonInfoActionPerformed

    private void buttoWykresyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoWykresyActionPerformed
        List <Surowiec> listaNaWykres = new ArrayList<>();
        for (int i=0; i<newEntry.size(); i++)
        listaNaWykres.add(Main.listaSurowcow.get(newEntry.get(i)));
        try {
            Wykres1 wykres = new Wykres1(listaNaWykres);
        } catch (IOException ex) {
            Logger.getLogger(GUIsurowce.class.getName()).log(Level.SEVERE, null, ex);
        }
        newEntry.clear();
    }//GEN-LAST:event_buttoWykresyActionPerformed
public void fillData() throws FileNotFoundException, IOException
	{
            
		DefaultTableModel defaultTableModel = new DefaultTableModel();
		defaultTableModel.addColumn("Nazwa");
		defaultTableModel.addColumn("J. handlowa");
		defaultTableModel.addColumn("Waluta");
		defaultTableModel.addColumn("Aktualna wartość");
		defaultTableModel.addColumn("Min wartość");
		defaultTableModel.addColumn("Max wartość");
		Surowiec inw = new Surowiec();
		for(Surowiec in: Main.listaSurowcow)
                {
                    //System.out.println("robimy coś");
			defaultTableModel.addRow(new Object[] {in.getNazwa(),in.getJednostkaHandlowa(),
                            "Złoty",in.getAktualnaWartosc(), in.getMinWartosc(), in.getMaxWartosc()});
                        //in.wyswietl();
                        
                }
		tabelaSurowcow.setModel(defaultTableModel);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoWykresy;
    private javax.swing.JButton buttomDodaj;
    private javax.swing.JButton buttomLosuj;
    private javax.swing.JButton buttonInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaSurowcow;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    // End of variables declaration//GEN-END:variables
}
