/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikacja;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import klasy.*;
import wykresy.*;

/**
 *
 * @author Elater
 */


public class GUIwaluty extends javax.swing.JInternalFrame {
    
private GUIwaluta guiwaluta = new GUIwaluta();
private Wykres1 wykres1;
boolean pressingCTRL=false;//flag, if pressing CTRL it is true, otherwise it is false.
Vector selectedCells = new Vector<int[]>();//int[]because every entry will store {cellX,cellY}
List <Integer> newEntry = new ArrayList<>();
/**
     * Creates new form GUIinwestorzy
     */
    public GUIwaluty() throws FileNotFoundException, IOException {
        
        setLocation(500, 30);
        initComponents();
                fillData();
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaWalut = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        buttomLosuj = new javax.swing.JButton();
        buttomDodaj = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        buttonInfo = new javax.swing.JButton();
        buttoWykresy = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista walut");

        tabelaWalut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaWalut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaWalutMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaWalut);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nowa waluta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setText("Nazwa:");

        jLabel2.setText("Lista krajów:");

        jLabel3.setText("Cena kupna:");

        buttomLosuj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomLosuj.setText("Losuj");
        buttomLosuj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomLosuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomLosujActionPerformed(evt);
            }
        });

        buttomDodaj.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttomDodaj.setText("Dodaj");
        buttomDodaj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttomDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomDodajActionPerformed(evt);
            }
        });

        jLabel7.setText("Cena sprzedaży:");

        text4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text4ActionPerformed(evt);
            }
        });

        buttonInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonInfo.setText("Info");
        buttonInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoActionPerformed(evt);
            }
        });

        buttoWykresy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttoWykresy.setText("Rysuj wykresy");
        buttoWykresy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoWykresy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoWykresyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text2)
                                    .addComponent(text1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text3)
                                    .addComponent(text4)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttomLosuj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttoWykresy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttomDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttomLosuj)
                    .addComponent(buttomDodaj))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInfo)
                    .addComponent(buttoWykresy))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttomLosujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomLosujActionPerformed
        
        try {
            Waluta inw = new Waluta();
            String kraje="";
            text1.setText(inw.getNazwa());
            for( String k: inw.getListaKrajow()) kraje+=k+" ";
            
            text2.setText(kraje);
            text3.setText(Double.toString(inw.getWartoscKupna()));
            text4.setText(Double.toString(inw.getWartoscSprzedazy()));
        } catch (IOException ex) {
            Logger.getLogger(GUIwaluty.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_buttomLosujActionPerformed

    private void buttomDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomDodajActionPerformed
       //Waluta zloty = new Waluta("Złoty", Main.listaZlotowek);
        
        List <String> lista = new ArrayList<>();
        String splited = new String(text2.getText());
        String[] splitedArray = null;
	splitedArray = splited.split(" ");
        for(String s: splitedArray) lista.add(s);
       
        Waluta inw = new Waluta(text1.getText(), lista,
               Double.parseDouble(text3.getText()), Double.parseDouble(text4.getText()));
       
        try {
            boolean unikat=true;
            for(Waluta in: Main.listaWalut)
            {
                if(in.getNazwa().equalsIgnoreCase(text1.getText())) unikat=false;
            }
            if(unikat==true) 
            {
                Main.listaWalut.add(inw);
                fillData();
            }
        } catch (IOException ex) {
            Logger.getLogger(GUIwaluty.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttomDodajActionPerformed

    private void text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text4ActionPerformed

    private void tabelaWalutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaWalutMouseClicked
        KeyListener tableKeyListener = new KeyAdapter() {

      @Override
      public void keyPressed(KeyEvent e) {
         if(KeyEvent.VK_CONTROL==e.getKeyCode()){//check if user is pressing CTRL key
            pressingCTRL=true;
         }
      }

      @Override
      public void keyReleased(KeyEvent e) {
         if(e.getKeyCode()==KeyEvent.VK_CONTROL){//check if user released CTRL key
            pressingCTRL=false;
         }
      }
        //buttonInfo.setEnabled(true);
          };
          MouseListener tableMouseListener = new MouseAdapter() {

      @Override
      public void mouseClicked(MouseEvent e) {
         if(pressingCTRL){//check if user is pressing CTRL key
            int row = tabelaWalut.rowAtPoint(e.getPoint());//get mouse-selected row
            //int col = tabelaSpolek.columnAtPoint(e.getPoint());//get mouse-selected col
            newEntry.add(row);//{row,col}=selected cell
            if(selectedCells.contains(newEntry)){
               //cell was already selected, deselect it
               selectedCells.remove(newEntry);
            }else{
               //cell was not selected
               selectedCells.add(newEntry);
            }
         }
      }
   };
   tabelaWalut.addKeyListener(tableKeyListener);
   tabelaWalut.addMouseListener(tableMouseListener);

    }                                         

    private void buttoInfoActionPerformed(java.awt.event.ActionEvent evt) {                                          
       if(!guiwaluta.isVisible())
        {
            guiwaluta.setVisible(true);
            JDesktopPane desktopPane = (JDesktopPane) getParent();
            desktopPane.add(guiwaluta);
                Waluta sp;
            try {
                sp = new Waluta();
                int currentRow = tabelaWalut.getSelectedRow();
                guiwaluta.fillData(sp.szukaj(tabelaWalut.getValueAt(currentRow, 0).toString()));
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                Waluta sp = new Waluta();
                int currentRow = tabelaWalut.getSelectedRow();
                guiwaluta.fillData(sp.szukaj(tabelaWalut.getValueAt(currentRow, 0).toString()));
                
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    

    }//GEN-LAST:event_tabelaWalutMouseClicked

    private void buttonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoActionPerformed
        if(!guiwaluta.isVisible())
        {
            guiwaluta.setVisible(true);
            JDesktopPane desktopPane = (JDesktopPane) getParent();
            desktopPane.add(guiwaluta);
            Waluta sp;
            try {
                sp = new Waluta();
                int currentRow = tabelaWalut.getSelectedRow();
                guiwaluta.fillData(sp.szukaj(tabelaWalut.getValueAt(currentRow, 0).toString()));
            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            try {
                Waluta sp = new Waluta();
                int currentRow = tabelaWalut.getSelectedRow();
                guiwaluta.fillData(sp.szukaj(tabelaWalut.getValueAt(currentRow, 0).toString()));

            } catch (IOException ex) {
                Logger.getLogger(GUIspolki.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonInfoActionPerformed

    private void buttoWykresyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoWykresyActionPerformed
        List <Waluta> listaNaWykres = new ArrayList<>();
        for (int i=0; i<newEntry.size(); i++)
        listaNaWykres.add(Main.listaWalut.get(newEntry.get(i)));
        try {
            Wykres2 wykres = new Wykres2(listaNaWykres);
        } catch (IOException ex) {
            Logger.getLogger(GUIsurowce.class.getName()).log(Level.SEVERE, null, ex);
        }
        newEntry.clear();
    }//GEN-LAST:event_buttoWykresyActionPerformed
public void fillData() throws FileNotFoundException, IOException
	{
            
		DefaultTableModel defaultTableModel = new DefaultTableModel();
		defaultTableModel.addColumn("Nazwa");
		defaultTableModel.addColumn("Kraje");
		defaultTableModel.addColumn("Cena kupna");
		defaultTableModel.addColumn("Cena sprzedaży");
		Waluta inw = new Waluta();
		for(Waluta in: Main.listaWalut)
                {
                    //System.out.println("robimy coś");
			defaultTableModel.addRow(new Object[] {in.getNazwa(),in.getListaKrajow(),
                            in.getWartoscKupna(), in.getWartoscSprzedazy()});
                        //in.wyswietl();
                        
                }
		tabelaWalut.setModel(defaultTableModel);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoWykresy;
    private javax.swing.JButton buttomDodaj;
    private javax.swing.JButton buttomLosuj;
    private javax.swing.JButton buttonInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaWalut;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    // End of variables declaration//GEN-END:variables
}
